/** Etiquetas legibles para las claves de clinical_records.ultrasound_findings (nombres de campo de MedDig). */
const LABELS = {
    'TIP-TRANS': 'Transductor',
    'UTERO-POS': 'Posición',
    'UTERO-FOR': 'Forma',
    'UTERO-BOR': 'Bordes',
    MIOMETRIO: 'Miometrio',
    ENDOMETRIO: 'Endométrio',
    'ESP-END': 'Espesor endometrial (mm)',
    'FS-DOUGLAS': 'F.S. Douglas',
    'OV-DER': 'Ovario derecho',
    'OV-IZQ': 'Ovario izquierdo',
    'OV-DER-M1': 'Ovario derecho - dimensión 1 (mm)',
    'OV-DER-M2': 'Ovario derecho - dimensión 2 (mm)',
    'OV-DER-M3': 'Ovario derecho - dimensión 3 (mm)',
    'OV-IZQ-M1': 'Ovario izquierdo - dimensión 1 (mm)',
    'OV-IZQ-M2': 'Ovario izquierdo - dimensión 2 (mm)',
    'OV-IZQ-M3': 'Ovario izquierdo - dimensión 3 (mm)',
    'LONG-MIOM': 'Long (mm)',
    'LONG-TRANSV-MIOM': 'Transverso (mm)',
    'LONG-ANT-POST-MIOM': 'Ant-Post (mm)',
    'O-HALL-DOP': 'Otros hallazgos y Doppler',
    'FS-OTROS': 'Especifique',
    FUM: 'F.U.M',
    EMBARAZOS: 'N° Embarazos',
    'POR-EMBARAZO': 'Por embarazo',
    'SAC-GES': 'Saco gestacional',
    'SAC-GES-DIM-MM': 'Saco gestacional (mm)',
    'SAC-GES-DIM-SEM': 'Saco gestacional (semanas)',
    EMBRION: 'Embrión',
    'ACT-CARD': 'Actividad cardíaca',
    'ACT-MOT': 'Actividad motora',
    LCR: 'LCR',
    'LCR-DIM-MM': 'LCR (mm)',
    'LCR-DIM-SEM': 'LCR (semanas)',
    'PLACA-CORIONICA': 'Placa coriónica',
    'PLA-COR-LOC': 'Localización placa coriónica',
    'SAC-VIT': 'Saco vitelino',
    PRESENT: 'Presentación fetal',
    SITUAC: 'Situación fetal',
    POSIC: 'Posición fetal',
    'VENT-CER': 'Ventrículo cerebral',
    CEREBELO: 'Cerebelo',
    'PLEX-COR': 'Plexos coroideos',
    COLUMNA: 'Columna',
    CORAZON: 'Corazón',
    ESTOMAGO: 'Estómago',
    'INT-GR': 'Intestino grueso',
    'RIÑONES': 'Riñones',
    VEJIGA: 'Vejiga',
    'MIEM-SUP': 'Miembro superior',
    'MIEM-INF': 'Miembro inferior',
    'PLAC-GR': 'Grado placentario',
    LOCALIZACION: 'Localización placentaria',
    'CORD-UMB': 'Cordón umbilical',
    DBP: 'DBP',
    'DBP-MM': 'DBP (mm)',
    'CIR-ABD': 'Circunferencia abdominal',
    'FEMUR-VAL': 'Fémur (mm)',
    'L-HUMER-VAL': 'Húmero (mm)',
    'TIBIA-VAL': 'Tibia (mm)',
    'HULAR-CUB-VAL': 'Cúbito (mm)',
    'HULAR-PER-VAL': 'Peroné (mm)',
    'HULAR-RAD-VAL': 'Radio (mm)',
    'CIR-CEF-MAN': 'Circunferencia cefálica',
    'PLAC-ESP': 'Espesor placentario',
    'PESO-EST-FET': 'Peso fetal estimado',
    'IDX-FET-TXT': 'Impresión diagnóstica fetal',
    'OG-NIV-LIQ-AMN': 'Líquido amniótico',
    CIT: 'Citología',
    'CIT-COND': 'Citología - conducta',
    COLP: 'Colposcopia',
    'AC-ACET': 'Ácido acético',
    LUGOL: 'Lugol',
    'NO-HUM': 'N° de húmero',
    NODF: 'N.O.D.F',
    NOPT: 'N.O.P.T',
};

function etiqueta(clave) {
    return LABELS[clave] || clave;
}

module.exports = { etiqueta };
